# Generated by Django 3.2.16 on 2022-11-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devbooksapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_in',
        ),
    ]
