# Generated by Django 3.2.16 on 2022-11-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devbooksapp', '0002_remove_book_published_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Published')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(0, 'Finance'), (1, 'Spiritual'), (2, 'Health'), (3, 'Leaderships'), (4, 'Biographies')], max_length=25),
        ),
    ]
