# Generated by Django 3.2.16 on 2022-11-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devbooksapp', '0004_auto_20221119_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
