# Generated by Django 3.2.16 on 2022-11-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devbooksapp', '0005_rename_name_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[(0, 'Finance'), (1, 'Spiritual'), (2, 'Health'), (3, 'Leaderships'), (4, 'Biographies')], max_length=20),
        ),
    ]
