# Generated by Django 3.2.16 on 2022-11-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devbooksapp', '0006_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('finance', 'Finance'), ('spiritual', 'Spiritual'), ('health', 'Health'), ('leadership', 'Leadership'), ('biographies', 'Biographies')], max_length=20),
        ),
    ]
