# Generated by Django 3.2.16 on 2022-11-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devbooksapp', '0008_rename_category_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-title']},
        ),
    ]
