# Generated by Django 3.2.16 on 2022-11-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devbooksapp', '0009_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default='0'),
        ),
    ]
