# Generated by Django 3.2.16 on 2022-11-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devbooksapp', '0011_alter_book_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
