# Generated by Django 3.2.16 on 2022-11-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devbooksapp', '0012_alter_book_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
