# Generated by Django 3.2.16 on 2022-11-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devbooksapp', '0013_rename_name_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='buy_button',
            field=models.URLField(default=None, max_length=100),
        ),
    ]
