# Generated by Django 3.2.16 on 2022-11-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devbooksapp', '0014_book_buy_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='buy_button',
            field=models.URLField(default='https://www.amazon.com/', max_length=100),
        ),
    ]
