# Generated by Django 3.2.16 on 2022-11-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devbooksapp', '0017_alter_book_buy_button'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='book',
            new_name='title',
        ),
    ]
