# Generated by Django 3.2.16 on 2022-11-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devbooksapp', '0018_rename_book_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='book',
        ),
    ]
